# 6) Create a node port type service lemp-service to expose 
# the web application, nodePort must be 30008.

apiVersion: v1
kind: Service
metadata:
  name: lemp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    app: lemp-wp