apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"python-service-nautilus","namespace":"default"},"spec":{"ports":[{"nodePort":32345,"port":8080}],"selector":{"app":"python_app"},"type":"NodePort"}}
  creationTimestamp: "2025-05-04T13:37:33Z"
  name: python-service-nautilus
  namespace: default
  resourceVersion: "2566"
  uid: 3ece0887-bea1-4bff-87c0-be78157866f6
spec:
  clusterIP: 10.96.241.232
  clusterIPs:
  - 10.96.241.232
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32345
    port: 5000 # changed 8080 to 5000
    protocol: TCP
    targetPort: 5000 # changed 8080 to 5000
  selector:
    app: python_app
  sessionAffinity: None
  type: NodePort
