# Create a node port type service lamp-service to expose the web application,
#  nodePort must be 30008.

apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort
  selector:
    app: lamp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008